plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.komentum'
version = '0.0.1-SNAPSHOT'

springBoot {
    mainClass = 'com.komentum.KomentumApplication'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}

test {
    useJUnitPlatform()
}

dependencies {
    // web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // webclient
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    // jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.mysql:mysql-connector-j'
    // redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    // Jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    // aws s3 api
    implementation 'software.amazon.awssdk:s3:2.31.63'
    // swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.mockito:mockito-inline:5.2.0'
    // test : h2 database
    testImplementation 'com.h2database:h2'
    // test : java-faker
    implementation('com.github.javafaker:javafaker:1.0.2') { exclude module: 'snakeyaml' }
    implementation 'org.yaml:snakeyaml:2.0'
    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

tasks.register('copyConfig', Copy) {
    from("${rootProject.projectDir}/backend_config/dev/monolithic") {
        include 'application.yml'
    }
    into './src/main/resources/'
}

tasks.register("copyTestConfig", Copy) {
    from("${rootProject.projectDir}/backend_config/dev/monolithic") {
        include 'application-test.yml'
    }
    into './src/test/resources/'
}

processResources.dependsOn(copyConfig)
processTestResources.dependsOn(copyTestConfig)