x-common-variables: &common-variables
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/
  SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${MYSQL_DATABASE}
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  GATEWAY_SERVICE_URL: http://gateway-service:8080

services:
  gateway-service:
    build:
      dockerfile: gateway-service/Dockerfile
      context: ..
    container_name: gateway-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "28080:8080"
    environment:
      <<: *common-variables
  discovery-service:
    build:
      dockerfile: discovery-service/Dockerfile
      context: ..
    container_name: discovery-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "28761:8761"
    environment:
      <<: *common-variables
  user-service:
    build:
      dockerfile: user-service/Dockerfile
      context: ..
    container_name: user-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      <<: *common-variables
  theme-service:
    build:
      dockerfile: theme-service/Dockerfile
      context: ..
    container_name: theme-service
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    env_file:
      - .env
    environment:
      <<: *common-variables
  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - "23306:3306"
  redis:
    image: redis:6.2.6-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped