x-common-variables: &common-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${MYSQL_DATABASE}
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  SECURITY_ALLOWED_ORIGIN_LIST: http://localhost:8080,http://localhost:28080,http://localhost:3000,"react 도메인 추가"

services:
  backend:
    image: louie8821/kakao-theme-maker:v1-dev
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - "28080:8080"
    environment:
      <<: *common-variables
  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - "23306:3306"
  redis:
    image: redis:6.2.6-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    volumes:
      - ./docker_redis/data:/data
      - ./docker_redis/config:/usr/local/etc/redis/redis.conf
